FROM golang:1.23.1-alpine3.19 AS builder

WORKDIR /app

# Instalar git
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./internal/worker

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/worker .

CMD ["./worker"] 